### ISSUE TITLE
jest 25: Cannot read property 'handleJestRunComplete' of undefined

### ISSUE THREAD

**Issue by ian-craig** [karanjitsingh/jstestadapter#58]
After upgrading from Jest 24.*.* to >= 25.1.0, I am hitting the following error when running jstestadapter.

```
Error: 12588, 2020/5/13, 09:26:43:651, JestTestFramework: Exception on await runCLI Error: Cannot read property 'handleJestRunComplete' of undefined, Stack: TypeError: Cannot read property 'handleJestRunComplete' of undefined
    at JestReporter.onRunComplete (node_modules\jstestadapter\TestRunner\TestFrameworks\Jest\JestReporter.js:10:36)
    at ReporterDispatcher.onRunComplete (node_modules\@jest\core\build\ReporterDispatcher.js:71:25)
    at TestScheduler.scheduleTests (node_modules\@jest\core\build\TestScheduler.js:280:28)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

> On Jest 25.0.0 I hit a separate error `Exception on await runCLI Error: this.jest.runCLI is not a function, Stack: TypeError: this.jest.runCLI is not a function` which appears to be fixed in Jest 25.1.0.

It appears that Jest is no longer doing some kind of binding that jstestadapter is expecting. When Jest calls `onRunComplete` on the reporter, the instance run doesn't appear to have callbacks.

**Comment by karanjitsingh** [comment]
@ian-craig, sorry for the super delayed response, I seem to have missed out on the notification. Let me take a look

**Comment by karanjitsingh** [comment]
@ian-craig I was able to repro the issue you mentioned for `25.0.0` but it seems to be working fine for me with `25.1.0` for the attached sample. Could you give me more details about your execution and the full logs?

Running the sample (Through vs dev console)
```
npm install
vstest.console.exe --TestAdapterPath:.\node_modules\jstestadapter package.json -- JSTest.TestFramework=Jest JSTest.DebugLogs=true
```
[jestrepro.zip](https://github.com/karanjitsingh/jstestadapter/files/4896266/jestrepro.zip)

**Comment by emluu** [comment]
@karanjitsingh I have also checked this for Jest ` 26.0.1` and it runs into the same problem. I've attached my logs and this is the full command line I executed with:

`D:\office\Build\OfficeNugetInit\gen\.versionless\buildxl.win-x64\sdk\sdk.qtest\bin\V150\Common7\IDE\Extensions\TestPlatform\vstest.console.exe /logger:console /logger:trx /platform:X64 /TestAdapterPath:e:\nugetcache\dullscript.1.0.2007.90901-dev\node_modules\jstestadapter D:\office\Build\DominoTemp\p\7\18ytaj60n84wh2zrgtzk9kkc\sandbox\qtest2\jest_withignored.config.js -- JSTest.TestFramework=Jest JSTest.NodePath=D:\office\Build\x64\debug\msoserviceplatform\src\Browser\App\Packages\Activities\UnitTests\TsTranspile\objd\x64\\test_dependencies\node.exe JSTest.DebugLogs=true -- RunConfiguration.ExecutionThreadApartmentState=STA`
[jstest.node.2020-7-11-09.46.02.4_186784.log](https://github.com/karanjitsingh/jstestadapter/files/4904440/jstest.node.2020-7-11-09.46.02.4_186784.log)
